-- AlterEnum
-- Add new platform values to Platform enum
ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'SNAPCHAT';
ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'LINKEDIN';
ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'TELEGRAM';
ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'YAHOO';
ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'OUTLOOK';
